name: CI & CD Production Environment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{github.event.repository.homepage}}
    needs:
      - test
    permissions:
      packages: write

    env:
     REGISTRY: ghcr.io
     IMAGE_NAME: ghcr.io/${{github.repository_owner}}/${{secrets.AZURE_CONTAINER_APP}}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      # Setup new docker builder for cache
      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{env.IMAGE_NAME}}:${{github.sha}}
            ${{env.IMAGE_NAME}}

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: ${{env.REGISTRY}}
          registryUsername: ${{github.repository_owner}}
          registryPassword: ${{secrets.REGISTRY_TOKEN}}
          containerAppName: ${{secrets.AZURE_CONTAINER_APP}}
          resourceGroup: ${{secrets.AZURE_RESOURCE_GROUP}}
          imageToDeploy: ${{env.IMAGE_NAME}}:${{github.sha}}
          targetPort: ${{secrets.PORT}}
